- run_tests.sh
Test rpc-maas against an rpc-ceph AIO deployment.
> Implement rpc-maas Integration testing

- .gitignore
- tests/setup-ceph-aio.yml
- tests/test-rgw.yml
- tests/test.yml
Adding a simple generic rgw test.
> Add rgw test

- ansible-role-requirements.yml
- ansible-role-test-requirements.yml
- playbooks/ceph-setup-logging.yml
- playbooks/deploy-ceph.yml
- tests/host_vars/localhost.yml
- tests/inventory
- tests/setup-ceph-aio.yml
- tests/setup-rsyslog-server.yml
- tests/test-logging.yml
We will test this by setting up an rsyslog-server, for testing only, on
the localhost.
> [CEPHSTORA-17] Setup rsyslog_client role on ceph hosts

- scripts/bootstrap-ansible.sh
Signed-off-by: Matthew Thode <mthode@mthode.org>
> bootstrap on non-test systems

- README.md
- docs/rgw_setup.md
- gating/pre_merge_test/run
- run_tests.sh
- scripts/bootstrap-ansible.sh
Changed up the script ceph-ansible to actually run "ansible" and created a new script ceph-ansible-playbook to run "ansible-playbook".    This should allow people doing deployments to run ansible commands.
Cleaned out some unneeded code from the scripts.    
Updated documentation
> Cephstora 88  rework ceph-ansible and cleanup scripts

- README.md
- ansible-role-requirements.yml
- playbooks/deploy-ceph.yml
- playbooks/group_vars/all/all.yml.sample
- playbooks/group_vars/mgrs/mgrs.yml.sample
- playbooks/group_vars/mons/mons.yml.sample
- playbooks/group_vars/osds/osds.yml.sample
Includes update to group_vars and site.yml sample files.
> CEPHSTORA-97 Bump ceph-ansible to v3.0.21

- docs/rpc-ceph-install.md
First Draft of Install documentation.
> CEPHSTORA-77 First Draft of Install doc for rpc-ceph release

- scripts/ceph-ansible_increment_release.sh
Remove a debug line that was added and left in accidentally.
> Remove debug line in script

- README.md
- scripts/bootstrap-ansible.sh
Some minor fixes to modules in Ansible were added, lets move to use
version 2.4.3.
> Bump to Ansible 2.4.3

- benchmark/fio_benchmark_cleanup.yml
- benchmark/fio_benchmark_setup.yml
Allow for mulitple benchmark_hosts to run fio test simultaneusly
> CEPHSTORA-135 Enable parallel fio benchmark runs

- playbooks/deploy-phobos-nodes.yml
Add server group to phobos lab deploy to enforce anti-affinity of client
vms.
> CEPHSTORA-134 Deploy clients using server group

- benchmark/README.md
- benchmark/rgw_benchmark_setup.yml
- phobos/cap-vars.yml
- playbooks/group_vars/all/00-defaults.yml
Adding deployment config for the phobos ceph capacity cluster deployment
> CEPHSTORA-149 Add capacity lab cluster config

- benchmark/fio_benchmark_cleanup.yml
- benchmark/fio_benchmark_run_tasks.yml
- benchmark/fio_benchmark_setup.yml
- benchmark/rgw_benchmark_run.yml
- benchmark/templates/README_fio.md.j2
- playbooks/deploy-phobos-nodes.yml
- playbooks/group_vars/benchmark_hosts/00-defaults.yml
- playbooks/templates/inventory_file.j2
Use fio_generate_plots that ships with fio to generate graphs of
bandwidth, iops and latency data
> CEPHSTORA-156 Generate graphs from fio benchmarks

- benchmark/fio_benchmark_setup.yml
Build fio 3.5 to replace fio 2.2.10 that ships with xenial
> CEPHSTORA-159 Build fio 3.5 for improved benchmark

- README.md
- ansible-role-requirements.yml
- playbooks/osd-configure.yml
- playbooks/rolling_update.yml
- scripts/ceph-ansible_increment_release.sh
Additionally, adjust the increment script to also retrieve the
infrastructure-playbooks for osd-configure.yml and rolling_update.yml.
> Bump ceph-ansible to v3.0.28

- README.md
- gating/pre_merge_test/run
- tests/test-vars-bluestore.yml
This will consist of 3 collocated bluestore OSDs per OSD host.
Additionally, remove unnecessary conditional inside the run_tests.sh.
> CEPHSTORA-173 Setup a Bluestore AIO

- docs/deployment-scenarios/CephNodeAddition.txt
- docs/deployment-scenarios/CephNodeAdditionJewel.txt
- docs/deployment-scenarios/Ceph_Standalone_Install.md
- docs/deployment-scenarios/RollingUpdates.yml
- docs/rgw_setup.md
- playbooks/group_vars/all/00-defaults.yml
- playbooks/group_vars/rgws/00-defaults.yml
- playbooks/purge-cluster.yml
- scripts/ceph-ansible_increment_release.sh
* Update docs from these locations:
https://github.com/rsoprivatecloud/rpc-deployments/tree/master/installs/ceph
https://one.rackspace.com/pages/viewpage.action?title=Ceph+-+Rolling+Updates+using+Ceph-Ansible&spaceKey=PPAGES
https://one.rackspace.com/pages/viewpage.action?title=Ceph+-+Deployment+Using+Ceph-Ansible&spaceKey=PPAGES
* Update defaults to reduce docs
* Add in purge-cluster script and add it to increment_release.sh script
> [CEPHSTORA-169] Update Docs for RPC-Ceph

- playbooks/deploy-phobos-nodes.yml
Cast client_count to int for int comparison
> CEPHSTORA-206 Fix phobos deploy under python3

- phobos/accessinfo.md
Documents various things about the PHOBOS lab environment:
How to create a user
Sample openrc file
Who to contact for information about the VPN
Basic info on the environment itself
> Phobos lab document

- disable-restart.yml
Playbook to push out ceph config without restarting services
> CEPHSTORA-38 Play to push config updates w/o restart

- playbooks/add-mgr-modules.yml
- playbooks/deploy.yml
- playbooks/group_vars/mgrs/00-defaults.yml
In luminous clusters enabled dashboard and balancer modules by default
> CEPHSTORA-225 Enable ceph mgr dashboard by default

- phobos/README.md
- phobos/VLANS.md
- phobos/cap-vars.yml
- phobos/perf-vars.yml
- playbooks/add-ceph-interfaces.yml
- playbooks/deploy-phobos-nodes.yml
- playbooks/templates/interface.cfg.j2
Adding ability to add VLANs to phobos deploy to separate public network
from cluster network.
> CEPHSTORA-215 Add VLAN Configuration to Phobos

- phobos/cap-vlan-vars.yml
- phobos/perf-vlan-vars.yml
- playbooks/deploy-phobos-nodes.yml
Skip the interface configuration play unless ceph_interfaces is defined
> CEPHSTORA-239 Configure vlans when ceph_interfaces

- playbooks/group_vars/all/00-defaults.yml
Add default tuning around scrubs and trims to reduce the performance
impact of backround scrub and trim activity.
> CEPHSTORA-237 Tune scrub/trim reduce perf impact

- playbooks/group_vars/all/00-defaults.yml
- playbooks/group_vars/mgrs/00-defaults.yml
Waiting for an authentication solution to enable everywhere
> CEPHSTORA-266 Do not enable mgr dash by default

- playbooks/group_vars/all/overrides.yml.sample
- playbooks/group_vars/benchmark_hosts/overrides.yml.sample
- playbooks/group_vars/mgrs/overrides.yml.sample
- playbooks/group_vars/mons/overrides.yml.sample
- playbooks/group_vars/osds/overrides.yml.sample
- playbooks/group_vars/rgws/overrides.yml.sample
Add some sample overrides files per group.
> CEPHSTORA-251 Sample overrides files

- ansible-role-requirements.yml
- docs/monitoring.md
- playbooks/add-mgr-modules.yml
- playbooks/deploy.yml
- playbooks/group_vars/all/00-defaults.yml
- playbooks/node_exporter.yml
- playbooks/prometheus.yml
- playbooks/templates/ceph_targets.j2
- playbooks/templates/node_targets.j2
- playbooks/templates/prometheus/config/scrapes/prometheus_config.j2
Include optional plays for installing and configuring prometheus and
node_exporter based on external ansible roles.
> CEPHSTORA-255 Prometheus and node_exporter plays

- ansible-role-requirements.yml
- docs/boostrap-as-non-root-user.md
- docs/dashboards.md
- inventory-sample
- playbooks/add-hosts.yml
- playbooks/deploy.yml
- playbooks/distribute-root-key.yml
- playbooks/files/grafana/dashboards.yaml
- playbooks/files/grafana/dashboards/ceph_cluster.json
- playbooks/files/grafana/dashboards/ceph_pools.json
- playbooks/files/grafana/dashboards/node-exporter-full.json
- playbooks/files/grafana/dashboards/node-exporter-server-metrics.json
- playbooks/grafana.yml
- playbooks/templates/grafana/datasources.yaml.j2
Playbook to optionally install grafana
> CEPHSTORA-258 grafana install playbook

- run_tests.sh
Simple symlink fix after the changes in the gating directory
> Change symlink to point at the right file

- CONTRIBUTING.md
Add a basic contributing guidelines file that can be built on. Include
information on utilising the reno tool.
> CEPHSTORA-305 Add contributing.md with reno information

- benchmark/README.md
documenting the need to set one of the benchmark options to true.
> README update

- ansible-role-requirements.yml
- phobos/vm-vars.yml
- playbooks/alertmanager.yml
- playbooks/deploy.yml
- playbooks/templates/prometheus/rules/ceph
- releasenotes/notes/alertmanager_playbooks-193a8d08ed82bc01.yaml
Adding play to install and configure alertmanager
> CEPHSTORA-292 Optional alertmanager play

- ansible.cfg
- docs/ops-internal/checking-for-config-changes.md
- library/ini_diff.py
- playbooks/check-for-config-changes.yml
- playbooks/phobos-bootstrap.yml
- playbooks/templates/sysctl.j2
- releasenotes/notes/check_config_changes-e30b58360953f9bd.yaml
Playbook to check for changes to sysctl tuning, ceph.conf and
transparent_huge pages.  Intention is to test before converting from
ceph-ansible to rpc-ceph or to test before upgrading rpc-ceph versions.
> CEPHSTORA-261 Check for config changes

- releasenotes/notes/CEPHSTORA-380-69f18aa9c470adfc.yaml
- releasenotes/notes/CEPHSTORA-382-versionbump-7e421b23f1651bc9.yaml
This should fix an error in the spacing for reno release notes.
> Spacing fix

- docs/howtorelease.md
> Added in doc on releasing

- gating/check/run
- requirements.txt
ansible-lint enablement for gating jobs.
> enable ansible-lint gating

- docs/howtorelease.md
Flushed out the release docs and updated the command  that runs the final release compilation.
> Update docs based on current release

- gating/check/run
Setting absolute/full path to ansible-lint command.
> Set absolute path to ansible-lint

- gating/check/run
Work around to get the gate jobs up and going.    This will just bypass the lint check for now.
> Force lint success

- README.md
- gating/check/run
- tests/setup-ceph-storage.yml
Update tests to support rpco rocky scenario
> CEPHSTORA-443 Add rpco_rocky scenario

- gating/check/run
- playbooks/add-ceph-interfaces.yml
- playbooks/add-repo.yml
- playbooks/phobos-bootstrap.yml
- playbooks/phobos-deploy-nodes.yml
Add tag to tasks with known and accepted linting issues so new issues
will be flag as errors.
> CEPHSTORA-464 Skip known linting issues

- gating/update_dependencies/pre
- gating/update_dependencies/run
- scripts/get_role_version.py
Automatically generate a release note when the update dependency job is
run to list all dependency version changes.
> CEPHSTORA-367 Create release note with dep update

- README.md
- ansible-role-requirements.yml
- gating/update_dependencies/run
- inventory-sample
- playbooks/deploy-ceph.yml
- playbooks/group_vars/all/00-defaults.yml
- playbooks/group_vars/all/all.yml.sample
- playbooks/group_vars/mgrs/mgrs.yml.sample
- playbooks/group_vars/mons/mons.yml.sample
- playbooks/group_vars/osds/osds.yml.sample
- playbooks/group_vars/rgws/rgws.yml.sample
- playbooks/purge-cluster.yml
- playbooks/rolling_update.yml
- releasenotes/notes/update_deps-61acec665afbf124.yaml
Upgrade ceph-ansible from v3.0.46 to v3.1.9 and update our dependency
tracking script to track v3.1 of ceph-ansible going forward.
> CEPHSTORA-441 Upgrade ceph-ansible to v3.1.9

- playbooks/add-repo.yml
- playbooks/templates/gpg-key-script.j2
Fix the add-repo play to access the gpg key by name so it does not
conflict with other existing gpg keys.
> CEPHSTORA-496 Dedicated gpg key for custom repo

- scripts/ansible-role-requirements-editor.py
- scripts/get_role_version.py
Simple path argument check to make checkmarx happy.
> CEPHSTORA-495 Fix the path traversals

- inventory-sample
CEPHSTORA-540: Adding repo_severs and haproxy_all groups to inventory-sample
> Adding repo servers group to inventory-sample
