rcbops/rpc-ceph

run_tests.sh

When IRR_CONTEXT=ceph it means this is being run from the MaaS repo
tests, we should not run the maas tests twice in that case.

Only run maas tests if we're not running from MaaS

---

scripts/bootstrap-ansible.sh

When the existing pip version matches the version of pip we're trying to
install it won't re-install it. We should just use this pip instead of
forcing the pip in /opt/ansible-runtime.

Use existing pip if pip doesn't reinstall

---

ansible-role-requirements-xenial.yml
ansible.cfg
playbooks/deploy-ceph.yml

Instead of cloning all the individual roles we should clone only the
overarching ceph-ansible repository and adjust our ansible.cfg to
include the roles inside ceph-ansible.
Additionally, pin the plugins repository to stable/pike to reduce the
impact of changes upstream.

Move to use single repository for ceph-ansible

---

playbooks/group_vars/all.yml
tests/test-vars.yml

The journal size should be 2 * expected throughput * filestore max sync
interval. Our expected throughput on our best non-SSD drives is 140MB/s.
filestore max interval has a default of 5. That would mean a journal
size of 14GB. Let's round that up to 20GB as a lazy and safe estimate,
for a start point for journal devices.

Set default journal size to 20GB

---

playbooks/deploy-ceph.yml

We shouldn't reference a test vars file in a playbook we plan to use in
produciton. The test-vars.yml file is already included via -e @ inside
the run_tests.sh - which is not designed to be run against production,
and is only designed to run an AIO for testing.

Remove vars_files from deploy-ceph.yml

---

tests/cleanup-ceph-storage.yml
tests/setup-ceph-storage.yml

When re-running the playbooks the test for logs will fail because there
is a good chance the osds are not on the same hosts - meaning additional
logs are created.
To fix this we should remove anything in /var/log/rsyslog/ on a new run.
Additionally, we can remove the "mount" cleanup since we no longer mount
the partitions - this is a relic from the initial implementation.
Finally, we should move the cleanup tasks into a separate file for
clarity.

Clean up rsyslog logs, and create cleanup.yml

---

playbooks/git-clone-repos.yml

Avoid deprecation warning by moving from using a reserved var name
"roles" and instead use "clone_roles".

Minimal fix for roles var

---

1
benchmark/README.md
benchmark/fio_benchmark.yml
benchmark/fio_benchmark_cleanup.yml
benchmark/fio_benchmark_run.yml
benchmark/fio_benchmark_setup.yml
benchmark/templates/fio_direct_read_test.cfg.j2
benchmark/templates/fio_direct_write_test.cfg.j2
benchmark/templates/fio_rw_mix.cfg.j2
benchmark/templates/fio_test_file_read.cfg.j2
benchmark/templates/fio_test_file_write.cfg.j2
tests/inventory
tests/setup-ceph-aio.yml
tests/test-vars.yml

Adds fio tests based on EBS benchmark procedures:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/benchmark_procedures.html
Adds a run of the ebs_benchmark to testing.

[CEPHSTORA-18] Add FIO benchmark playbook

---

tests/setup-ceph-storage.yml
tests/test-vars.yml

Using the rpc_ceph_test_osd_size var we can now set the size of the osd
and journal devices.
We setup 4 per host, and there are 3 OSD hosts, so that will mean we
need 12x rpc_ceph_test_osd_size spare on the AIO localhost.
In order to use this we will need to ensure the osd_journal_size is
rpc_ceph_test_osd_size/3 otherwise the journals will be too big for the
journal partition.

Allow the size of the osd/journal devices to be set

---

tests/cleanup-ceph-storage.yml
tests/setup-ceph-storage.yml
tests/test-vars.yml

We were building 3 OSDs per OSD host at 10GB each + a journal, this
equated to 120GB (40/host), which is quite a storage footprint for an
AIO.
We don't need to build that many OSDs, and we can also reduce the size
of each disk used, as well as the journal. By dropping to 2 drives per
host + journal, and setting the size to 3GB each, we can reduce this to
27GB instead of 120.
If we need further space we could consider removing one of the OSD
hosts.

Reduce size of AIO build

---

requirements.txt
tests/host_vars/osd2.yml
tests/inventory
tests/test-vars.yml

We're currently hitting a number of issues gating rpc-ceph at the
moment.
1. Because OSDs were recently reduced from 3 to 2, the ceph cluster is
now always in a non-healthy state.  Additionally, we're seeing the
`Create fiobench pool` task fail because "pg_num 100 size 3 would
mean 984 total pgs, which exceeds max 800 (mon_max_pg_per_osd 200 *
num_in_osds 4)".
2. pip_install is dropping the UCA repo, resulting in the ceph packages
installed on localhost (for fiobench testing) are different than
those installed throughout the rest of the cluster.
3. When we deploy rpc-maas, localhost fails to add the apt_key for
https://repos.influxdata.com/.  This key gets installed fine inside
all containers and while I'm unsure of the specifics it appears that
this is due to urllib3 being installed on …

Unblock failing gate

---

tests/test-vars.yml

We should use UCA, it'll provide newer packages, and we shouldn't test
against packages we wouldn't deploy in prod. Since the change only
applied to gating it would mean we are testing against packages we don't
use in prod.

Remove uca_enable: False

---

tests/test-rgw.yml

The scbench pool cleanup needs the mon_allow_pool_delete setting to be
true to work properly. We can set this on the fly, if it isn't set, and
ensure it is set again before we clean it up.
Longer term we may want to move this kind of bench to the fiobench
tasks, and use the benchmarking as a proof that Ceph is working
properly.

Fix cleanup of scbench pool after test-rgw

---

tests/test-vars.yml

We don't use the MaaS api which is giving us some fake results when
monitoring would fail, but is showing up as passing still.
We can fix this by enabling it and specifying the maas_entity_name to be
the ansible_hostname rather than the inventory_hostname for tests since
localhost will not show up as an entity.
These settings are all setup in /etc/openstack_deploy/user_*_vars.yml
for the OpenStack installs, but are not configured for MaaS at all.

[CEPHSTORA-51] Use maas_use_api for Ceph tests

---

README.md
run_tests.sh
scripts/bootstrap-ansible.sh

If bootstraping OSA and rpc-ceph from the same box they can interfere
with eachother (not install needed deps for instance).  Since all we
need is ansible-playbook just run it from the venv directly.

RO-3487 Don't use the same ansible venv as OSA.

---

run_tests.sh

instead of calling rpc-ceph and having ansible installed to /opt/ansible-runtime like it should have, it was using tox's pip in /var/lib/jenkins/workspace/RPC-IRR_rpc-maas-master-xenial-ceph/rcbops/rpc-maas/.tox/functional/bin/pip and installing it to /var/lib/jenkins/workspace/RPC-IRR_rpc-maas-master-xenial-ceph/rcbops/rpc-maas/.tox/functional/lib somewhere
and because we were using export ANSIBLE_BINARY="ansible-playbook", it was finding the ansible-playbook command in  /var/lib/jenkins/workspace/RPC-IRR_rpc-maas-master-xenial-ceph/rcbops/rpc-maas/.tox/functional/bin but now rpc-ceph sets ANSIBLE_BINARY="/opt/rpc-ceph_ansible-runtime/bin/ansible-playbook", it pukes because ansible wasn't installed there
This change will set ANSIBLE_BINARY correctly if it …

 CEPHSTORA-69 Changes for rpc-maas/tox

---

scripts/bootstrap-ansible.sh

The hardcoded path "/opt/rpc-ceph_ansible-runtime/bin/ansible-playbook" is used in the bootstraph.sh script and should be replaced with the environment variable $ANSIBLE_BINARY

 CEPHSTORA-70 Replacing hardcoded path

---

gating/post_merge_test
gating/pre_merge_test/run

This commit updates rpc-ceph to use the standard rpc-gating hook
layout.  With this change in place, the rpc-ceph jobs can be moved to
using the standard jobs defined in rpc-gating's
standard_job_postmerge.yml and standard_job_premerge.yml files.

CEPHSTORA-49 Update to use standard gating layout

---

README.md
run_tests.sh
scripts/bootstrap-ansible.sh

This patch creates a wrapper "ceph-ansible" that ensures that the
correct Ansible version (and dependencies) can be installed for
ceph-ansible specifically are used.
Additionally, this removes the installation of tox and bindep which
aren't required. Documentation has been updated to reflect this. This
should make it easier for operators since they won't have to load into
the specific venv and can call the correct version using "ceph-ansible"
instead.

[CEPHSTORA-68] Use correct version of Ansible for ceph-ansible

---

gating/pre_merge_test/run

The {post,pre}_merge_test/run script was referencing the venv for
ceph, we should move it to use the ceph-ansible binary.

Adjust path for ceph-ansible binary

---

benchmark/fio_benchmark_setup.yml
playbooks/group_vars/all.yml
tests/test-rgw.yml
tests/test-vars.yml

Overriding some ceph-ansible defaults to better align the general install scripts with a standard RPC customer environment.   There could be other overrides needed for a customer on case by case bases but these defaults were provided by Support/Development.

Cephstora-16  Overriding some ceph-ansible defaults for RPC

---

playbooks/group_vars/all.yml
tests/test-vars.yml

We need to set the default pg num and pgp num down from 128 for testing,
128 creates pools that are too big and causes ceph radosgw to not start.
To do this properly this patch sets up a "ceph_conf_overrides_extra"
variable that is combined with ceph_conf_overrides_all to allow
additional settings to be specified that will overwrite the existing
ones in group_vars, but still use settings that aren't specifically
overwritten.
This saves the deployer having to completely respecify the var including
all defaults that they may not want to change at all.

[CEPHSTORA-86] Allow defaults to be overridden

---

playbooks/ceph-setup-logging.yml
playbooks/deploy-ceph.yml

The logging role doesn't continue to update logs that are shipped, this
causes issues when the role is run but services haven't started properly
yet.
This PR adds a pause in that will wait for 10 seconds to allow the
services some time to start up.
This should hopefully alleviate some of the logging test isues we've
seen in the gate.

Pause before setting up logging

---

playbooks/group_vars/rgws.yml

We should update the description and service name to show that it is a
Ceph endpoint rather than a Swift one.

CEPHSTORA-87 Update Ceph keystone endpoint details

---

docs/rgw_setup.md

This is the first draft at a document detailing instruction for setting up the Ceph Object Gateway in three different use cases
1.   Ceph rgw install 
2.   Ceph rgw install with a OpenStack Keystone only. (No other OpenStack components)
3.   Ceph rgw install with Openstack Keystone and It's used as a replacement for OpenStack Swift
To include:
Any rpc-maas bit?
review:  
variables in  https://github.com/rcbops/rpc-ceph/blob/master/playbooks/ceph-keystone-rgw.yml

CEPHSTOR-87 [WIP]  rgw docs initial draft

---

playbooks/group_vars/all.yml
tests/test-vars-rgw.yml

Ceph-ansible currently doesn't default the radosgw_keystone_ssl value,
we should default this to false. Until
https://github.com/ceph/ceph-ansible/pull/2355 merges.

Default radosgw_keystone_ssl to false

---

benchmark/group_vars

Using anisble to run the fio benchmarks requires access to the group vars since those .yml files have been separated out of the playbooks dir

CEPHSTORA-92 Running benchmarks needs reference to group_vars

---

README.md
gating/pre_merge_test/run

rpc-maas uses rpc-ceph to test the code related to monitoring a Ceph
deployment. rpc-ceph uses rpc-maas to test that that MaaS monitoring
using the master branch works. When testing the repository rpc-maas, the
MaaS tests run by rpc-ceph need to be disabled. IRR_CONTEXT has been
used to determine if the tests should be run however that is broken in
`gating/pre_merge_test/run` due to it being set to RE_JOB_BRANCH which
is only used in post-merge jobs and because it can't be overridden.
This change fixes the use of IRR_CONTEXT so that it can be set in
rpc-maas and adds a new variable, TEST_RPC_MAAS, that is more
descriptive with regards to its purpose. Once this is merged and
rpc-maas has switched to using TEST_RPC_MAAS, IRR_CONTEXT can be
removed.

RE-1276 Fix testing rpc-ceph with rpc-maas

---

phobos/simple_deployment.md

This document lays out an rpc-ceph deployment in the phobos lab using 
1 vm for admin
1 vm for rsyslog
5 OnMetal boxes as OSD nodes
This is a first pass with the eventual goal of creating an automated deployment

CEPHSTORA-76 First Draft of Phobos Deploy doc

---

gating/pre_merge_test/run

Since the IRR changes were removed MaaS tests only work from the MaaS
side. This is because the RE_JOB_SCENARIO for ceph tests is "functional"
and not "ceph".
We can work around this by setting the TEST_PLAYBOOK var to be tests.yml
manually instead of relying on the if statement inside the maas scripts.

CEPHSTORA-99 Fix MaaS integration

---

playbooks/ceph-setup-logging.yml
tests/setup-ceph-aio.yml

Sometimes the tests fail because the services haven't created their logs
yet, and so they don't exist when tested.
We should change the order so that we run the benchmark and RGW tests
before we setup the logging to allow additional time for the logging to
be setup.

Adjust order of log configuration

---

tests/host_vars/allsvc.yml
tests/host_vars/keystone1.yml
tests/host_vars/localhost.yml
tests/host_vars/mon1.yml
tests/host_vars/mon2.yml
tests/host_vars/osd1.yml
tests/host_vars/rgw1.yml
tests/host_vars/rsyslog1.yml
tests/test-vars-rgw.yml
tests/test-vars.yml

In order to create an automated and integrated AIO we need to ensure the
RPC-Ceph builds are running on the same network range as the RPC-O
deploys, and that the container settings match.
This PR adjusts those settings.

CEPHSTORA-102 Match networking and container settings to RPC-O

---

README.md
ansible-role-requirements.yml
ansible.cfg
gating/pre_merge_test/run
playbooks/ceph-rgw-haproxy.yml
playbooks/git-clone-repos.yml
playbooks/group_vars/all/00-defaults.yml
tests/ansible-role-test-requirements.yml
tests/inventory
tests/setup-ceph-aio.yml
tests/test-vars-rgw.yml
tests/test-vars.yml

We should setup haproxy when the haproxy_all host group is specified,
and when rados gw hosts exist. This shouldn't be determined by the
OpenStack integration, and Ceph should manage it's own VIP.
This PR moves the playbook into "playbooks" dir and makes adjustments to
the role-requirements, group_vars defaults, README and base inventory
for testing.
Additionally, to ensure roles/plugins for the Ceph roles, that would
overlap with any existing deploys - we should name space the roles,
e.g. use "ceph_roles". This will mean that issues don't arise as a
result of other deployments using the same roles and overwriting the
existing Ceph roles.

CEPHSTORA-105 Setup HAProxy outside of testing

---

tests/host_vars/osd2.yml

This host was missed off when the addresses were changed to match up
with the existing RPC-O AIO.
This PR fixes that.

Fix Addr for osd2 host in gating

---

docs/rpc-ceph-install.md

A link in the install documentation was moved:
installs/newton/RPCO_Ceph-Ansible_install.md → installs/ceph/RPCO_Ceph-Ansible_install.md

CEPHSTORA-115   HotFix to repair broken link

---

tests/test-logging.yml

Our logging test is flakey, in manual testing I've seen this issue once,
and the log did exist - so adding a retry to try and reduce the number
of failed gates we see as a result of the logging problem.

CEPHSTORA-103 Retry log checks until success

---

benchmark/fio_benchmark_setup.yml
tests/test-rgw.yml

For the pools we create as part of RPC-Ceph testing/benchmarking we
should ensure the correct application is set.
This will prevent WARN messages that would generate alerts/tickets when
running benchmarking on customer environments.

CEPHSTORA-118 Set application for rpc-ceph created pools

---

README.md
ansible-role-requirements.yml
playbooks/group_vars/osds/osds.yml.sample

The fix to ensure application types are set on OpenStack pools has been
merged and backported into v3.0, with the new tag v3.0.25. This will
ensure we stop receiving false WARNING messages for our ceph mon checks
in MaaS.

CEPHSTORA-114 Bump ceph-ansible to v3.0.25

---

tests/test-vars.yml

A bug in the way apparmor and overlayfs work together, that exists in
16.04 means that redeploying on the same host will fail if we use
overlayfs.
We should default to use dir as the backend store for containers.

CEPHSTORA-82 Use dir instead of overlayfs

---

benchmark/README.md
benchmark/rgw_benchmark.yml
benchmark/rgw_benchmark_cleanup.yml
benchmark/rgw_benchmark_run.yml
benchmark/rgw_benchmark_setup.yml
benchmark/templates/rgw_bench_test.conf.j2
tests/setup-ceph-aio.yml
tests/test-vars.yml

Setup:
Install the hummingbird binary
Setup the bench.conf configuration file with common defaults
Create a ceph user "testuser" to use for the benchmark
Create a subuser "swift" under "testuser" for the benchmark
Run:
Run the hummingbird benchmark and save the results in a log file
Cleanup:
Remove the bench configuration file and the hummingbird binary
Delete both the subuser and the user created for the benchmark

CEPHSTORA-28  Adding in an rgw benchmark using the hummingbird bench tool

---

README.md
ansible-role-requirements.yml
scripts/ceph-ansible_increment_release.sh

Additionally, fix ceph-ansible increment release to only focus on v3.0.x
now that the v3.1 beta and rc tags exist.

Bump ceph-ansible to v3.0.27

---

README.md
gating/pre_merge_test/run
tests/inventory_rgw
tests/inventory_rpco
tests/rpco_vars/cinder.yml.ceph
tests/rpco_vars/user_rpc_ceph_vars.yml
tests/setup-ceph-aio.yml
tests/setup-containers.yml
tests/test-vars-openstack.yml

Add an rpc-o integration "rpco_newton" scenario.
This builds a base-kit from the newton-rc branch, using only the
following services: Nova, Glance, Keystone, Cinder, Neutron.
In order to build this in a one time go without having to redeploy
certain services for config updates, we deploy in the following order:
* Bootstrap RPC-O ansible
* Bootstrap RPC-O AIO
* Replace env.d/cinder.yml to run is_metal: False
* Deploy RPC-O up until Keystone
* Add configuration options for Ceph
* Deploy Ceph
* Add configuration options for RPC-O
* Deploy Rest of RPC-O (Glance, Cinder, Nova, Neutron)
* Deploy tempest, then test deployment using tempest

CEPHSTORA-131 Add RPC-O Integration gate

---

gating/pre_merge_test/run
tests/rpco_vars/user_rpc_ceph_vars.yml
tests/test-vars-openstack.yml

The RPC-O AIO runs on perf2-15 because the general1-8 does not suffice.
We should adjust the RPC-Ceph gate to be able to do the same, so that
the integrated AIO can work more reliably.
In order for this to happen we need to adjust how we pass the values for
the BOOTSTRAP_OPTS and just use the vars we already had specified.

CEPHSTORA-151 Adjust run script to work with perf2-15

---

README.md
playbooks/group_vars/all/00-defaults.yml
playbooks/group_vars/mgrs/00-defaults.yml
playbooks/group_vars/mons/00-defaults.yml
playbooks/group_vars/osds/00-defaults.yml
playbooks/group_vars/rgws/00-defaults.yml

In some cases you want group specific overrides to apply to a host, for
example you may want to override some RGW settings to only RGW hosts.
However, you may want to keep the defaults. This is specifically
important when adjusting the RGW settings for OpenStack integration.
In order to do this we add an additional setting for each group:
ceph_conf_overrides_rgw_extra
ceph_conf_overrides_mon_extra
ceph_conf_overrides_mgr_extra
ceph_conf_overrides_osd_extra
These will apply to only the hosts in that group, and will take
precedence but not squash existing settings.
Only ceph_conf_overrides_extra will take precedence over these settings
per group,and will be applied to all hosts.

CEPHSTORA-150 Allow group specific overrides

---

tests/rpco_vars/user_rpc_ceph_vars.yml
tests/setup-ceph-aio.yml
tests/setup-swiftoperator-user.yml
tests/test-vars-openstack.yml

This requires #150 to merge first, and enables teh swiftoperator user
within Keystone, as well as runs the Swift Tempest tests to ensure Ceph
RGW is working properly.

CEPHSTORA-152 Enable Swift Tempest tests

---

phobos/cap-vars.yml
phobos/perf-vars.yml
playbooks/group_vars/all/00-defaults.yml

To ensure no defaulted passwords exist we should remove the default
password and only set this for testing.

Remove defaulted rgw_bench password

---

README.md
tests/setup-ceph-aio.yml
tests/test-vars-rgw.yml

To reduce the runtime of the functional test, we can run the
Benchmark tests against the Keystone/RGW integration test only. This
test is already shorter because it does not run the MaaS installation
steps.
In this way we reduce the length of time for the functional and RPC
integration tests and still ensure that benchmarking is tested.

CEPHSTORA-158 Only run benchmark tests during Keystone integration

---

gating/pre_merge_test/run
tests/setup-ceph-aio.yml
tests/setup-data-disk.yml

In #118 we fixed the integrated build to work against perf2-15 flavor,
to match what is used by the RPC-O gate.
This fixes the regular rpc-ceph AIO to work on perf2-15, by copying the
approach taken by OSA. This will allow us to adopt the perf2-15 if we
run into performance/memory issues in the future.

CEPHSTORA-155 Let regular AIO run in perf2-15

---

benchmark/README.md
benchmark/fio_benchmark_cleanup.yml
benchmark/fio_benchmark_setup.yml
phobos/cap-vars.yml
phobos/perf-vars.yml
playbooks/group_vars/benchmark_hosts/00-defaults.yml
tests/test-vars.yml

Updating the default for rbd direct block benchmarking to use a 4k
block size.

CEPHSTORA-157 Set default rbd bench to 4k block size

---

benchmark/ansible.cfg
playbooks/ansible.cfg
tests/ansible.cfg

To run the playbooks from the playbooks directory you would need the
ansible.cfg linked.

Link ansible.cfg into tests/benchmark/playbooks

---

tests/setup-data-disk.yml
tests/test-vars.yml

In the integrated build RPC-O has already setup the disk partitions,
this means that it won't run unless
bootstrap_host_data_disk_device_force is set to True, since it isn't set
at all the task fails.
This PR defaults to false, which will work for the RPC-O integration
build and the normal rpc-ceph builds on perf2-15 instances.

CEPHSTORA-171 Default bootstrap_host_data_disk_device_force

---

gating/pre_merge_test/run

In https://github.com/rcbops/rpc-maas/pull/449 there is a requirement
for some password vars that are otherwise not set. This will cause our
rpc-ceph job to fail, to get ahead of the game this PR adds the vars
file as an overrides file for the gate jobs that utilise MaaS.

Add MaaS secrets to ansible run

---

playbooks/ceph-keystone-rgw.yml
requirements.txt

python-keystoneclient fails to install because a requirement for PyYAML
3.0.12 is installed. We should use this as a chance to update our
requirements file.

CEPHSTORA-185 Fix requirements for PyYAML

---

README.md
ansible-role-requirements.yml
playbooks/group_vars/all/00-defaults.yml
playbooks/group_vars/osds/osds.yml.sample
playbooks/group_vars/rgws/00-defaults.yml

Additionally, clear up vars that we set that match the default of
ceph-ansible (and are therefore unrequired), unless they are used
by playbooks that don't import the ceph-defaults role.
This bump fixes the spurious restarts due to config_template not
honouring ordering of configuration files. CEPHSTORA-166

Bump ceph-ansible to v3.0.29

---

playbooks/group_vars/all/00-defaults.yml
tests/setup-ceph-storage.yml

We should default this to the ceph-ansible default which is "true". This
was set to false when the initial AIO was setup, but should not have
been left in place.
In order for that setting to work we need to configure OSD hosts to
remounte /sys rw for the AIO containers.

CEPHSTORA-199 Fix disable_transparent_hugepage

---

benchmark/fio_benchmark_setup.yml

Removing checks for undefined variables that are blocking benchmark
runs.

CEPHSTORA-193 Revert conditions failing benchmarks

---

playbooks/ceph-keystone-rgw.yml

To avoid leaking passwords when configuring keystone endpoints, we
should set no_log: True, this will mean the passwords aren't shown when
we use verbose mode, or callback plugins.

CEPHSTORA-218 Set no_log: True on tasks involving passwords

---

tests/host_vars/osd2.yml

The RPC-O integration jobs are failing because the glance/cinder hosts
can connect to the mon hosts but can't connect to the osd2 host. The
netmask was incorrect on the osd2 host only.

CEPHSTORA-175 Fix netmask on osd2

---

phobos/cap-vars.yml
phobos/perf-vars.yml
playbooks/deploy.yml
playbooks/ssacli-install.yml

Playbook to install ssacli at version default latest or ssacli_version.
By default the play will not be included in a deploy, but can be enabled
with install_ssacli: true

CEPHSTORA-234 Add play to install ssacli

---

scripts/ceph-ansible_increment_release.sh

Release increment currently only git adds the deploy-ceph.yml playbook
and not the other playbooks we create. This PR fixes that.

Increment release should include all changed playbooks

---

phobos/cap-vars.yml
phobos/perf-vars.yml

In a previous change I munged the subnet cidr for the ironic network in
the phobos environment.

Fix cidr for ironic network in sample vars file

---

tests/setup-ceph-storage.yml

The gate is failing because the parted module is not able to find
"parted".

Add parted to package installs

---

gating/pre_merge_test/run

The maas jobs are failing with an apt update failure. This should help
debug the issue.

Add apt-transport-https package for MaaS test

---

gating/pre_merge_test/run

The integrated build jobs for Newton require parted to be installed, the
new gate image does not have parted. This PR installs parted.

CEPHSTORA-176 Add parted package to integrated build jobs

---

gating/pre_merge_test/run

The change to use nodepool in Releng has meant some packages are not
available on the base image (iptables/parted/util-linux). We should
install these so the integrated builds can succeed.

CEPHSTORA-272 Install required packages

---

gating/pre_merge_test/run

The gate jobs create instances with really long names resulting in job
failures for OSA containers. This PR removes the setting of the hostname
to match the host itself.

CEPHSTORA-278 Don't set hostname to match host

---

benchmark/fio_bench/group_vars
benchmark/rgw_bench/group_vars

Since moving fio_bench and rgw_bench plays into their own directories we
should link the group_vars into this directory to ensure the group_vars
are read when calling the individual playbooks.

CEPHSTORA-277 Add group_vars to benchmark directories

---

gating/pre_merge_test/run

Gating issue relating to no uuid-runtime package being available in the
base gate image.

Add uuid-runtime package

---

gating/pre_merge_test/run
tests/setup-ceph-storage.yml

We weren't setting the action plugins path correctly in our last
release, which meant the purge-cluster.yml playbook didn't work. This
has been fixed, but we should test the playbook as part of the build
jobs to ensure this works.

CEPHSTORA-280 Test purge-cluster playbook

---

gating/check/run
scripts/bootstrap-ansible.sh

We don't need make as part of the production environment for deploying
Ceph, so we should set it up solely for the purposes of generating the
documentation.

Move make package install to run_tests instead of bootstrap-ansible

---

playbooks/group_vars/all/00-defaults.yml
playbooks/group_vars/rgws/00-defaults.yml
releasenotes/notes/rgw_endpoint_ironic-ddb182811e9413aa.yaml

Ironic requires the Swift Account to be in the URL, there are RGW
settings to achieve this.
Additionally, the endpoint URL needs to be adjusted accordingly.

CEPHSTORA-283 Adjust RGW options for use with Ironic

---

benchmark/README.md
benchmark/fio_bench/fio_benchmark_run_tasks.yml
benchmark/fio_bench/fio_benchmark_setup.yml
benchmark/fio_benchmark.yml
playbooks/group_vars/benchmark_hosts/00-defaults.yml

First pass of refactoring benchmark code.
This should help running specific benchmarks and create only required devices in the rados pool.

CEPHSTORA-256:  fio benchmark code refactoring

---

phobos/cap-vars.yml
phobos/cap-vlan-vars.yml
phobos/perf-vars.yml
phobos/perf-vlan-vars.yml
playbooks/phobos-deploy-nodes.yml
playbooks/phobos-deploy.yml
playbooks/templates/inventory_file.j2

Fixing the order of the phobos-deploy.yml play so ceph_interfaces are
configured before the write-hosts play attempts to lookup the interface
ips.  The ironic boolean needed a default value.  Removed ansible_user
and ansible_become from inventory file.

CEPHSTORA-302 Fix phobos play order and vars

---

gating/check/run

Previously, we were installing pip unconstrained. This commit uses the
same mechanism to install pip as is used elsewhere in rpc-ceph's tests.
Additionally, we spawn a subshell to unset PYTHONPATH, which is being
set in rpc-maas's tox invocation. This is preventing the python3 venv
from being used correctly when these rpc-ceph tests are invoked via
rpc-maas.

RE-1617 Fix version of pip in rpc_component venv

---

playbooks/group_vars/benchmark_hosts/00-defaults.yml

Setting defaults upfront instead of doing it inline. This addresses comments in PR 187

CEPHSTORA-310 set default of bench variables

---

ansible-role-requirements.yml
ansible.cfg
gating/check/run
tests/ansible-role-test-requirements.yml
tests/build-containers.yml

We shouldn't use head of branch for a specific release. We should
instead use the released versions that will remain stable.
Additionally, ceph-ansible carries all the plugins it requires, we
should utilise those instead of getting the openstack-ansible-plugins
directory.

CEPHSTORA-191 Fix versions of rsyslog/haproxy etc

---

ansible-role-requirements.yml
tests/ansible-role-test-requirements.yml

The OSA plugins are required to perform keystone integration.
Another solution would be to utilize the Shade modules, and use the
openstack_openrc role to add a default clouds.yaml. However, until we
use Ansible 2.5.0 the os_keystone_endpoint module is not available, and
we wouldn't be able to create the endpoints. As such this is the
simplest approach to fixing up our integration jobs and ensuring we can
create keystone endpoints/users/roles/services.

CEPHSTORA-321 Add OSA plugins as a base role

---

playbooks/group_vars/osds/00-defaults.yml
playbooks/tune-cpufreq.yml
releasenotes/notes/cpuidle_states-32a3a07d5b6202d0.yaml

This PR adds 2 variables, "enable_cpuidle_states" and
"disable_cpuidle_states", which will allow the operator to specify the
states to disable or enable.
NB if you specify the same values in both disable or enable it will
enable them. (Enabling takes precedence).

CEPHSTORA-325 Specify cpu states to adjust and allow enabling

---

scripts/scripts-libs.sh

https://review.openstack.org/#/c/579927/ fixed a bug for OSA which would
be mirrored here. We should follow the fix.

Fix version of get-pip

---

gating/update_dependencies/run
scripts/ansible-role-requirements-editor.py

We recently added an automated job to update the deps for ceph-ansible
automatically. This PR includes updates to all other roles that we use
for both testing and production.
This PR also adjusts the way the ansible-role-requirements-editor.py
functions, meaning that you can specify the repo to update by its URL,
if no name is present it will take that as the identified, allowing us
to update roles such as the plugins role, which does not have a name and
src that are the same.

CEPHSTORA-330 Automatically update all Ansible roles

---

gating/check/run
tests/rpco_vars/user_rpc_ceph_vars.yml
tests/setup-data-disk.yml

In Queens release of OSA the inventory directory moved from the
playbooks dir to the top level of the OSA directory.
Additionally, the haproxy user_config moved into it's own scenario file
which needs to be included.

CEPHSTORA-323 Fix rpco_integration for Queens+

---

releasenotes/notes/version_bump310718-121a3d6eca29bd59.yaml

In https://github.com/rcbops/rpc-ceph/pull/213/ we bumped the versions
of various Ansible roles. This adds a release note for that.

Add release note for version bump

---

gating/check/run

There seems to be an issue with the master branch of the repo used in
the file tests/ansible-role-test-requirements.yml for
rpc-maas/tests/common.  Using a previous branch seems to work ok but
It's not a good idea for rpc-ceph to pin it's rpc-maas testing to a
specific branch.  The working branch is:
version: b146d649e675d748a58af238c7b37138b8194f1f
name: rpc-maas/tests/common
scm: git
src: https://git.openstack.org/openstack/openstack-ansible-tests
version: master

Turning the rpc-maas tests off by default

---

releasenotes/notes/update_deps-b91278014e746760.yaml

There is a problem starting a line in release notes with a special
character `.

Correcting error in release notes.

---

README.md
gating/check/run

Adding in a new scenario to test and verify that release notes
will build correctly.  This should be the first step to creating
a gating job for it.

Add a new RE_JOB_SCENARIO build_releasenotes

---

releasenotes/notes/CEPHSTORA-380-69f18aa9c470adfc.yaml

Added release notes for latest dependency update.    This was an experiment.   From now on the release notes should probably added to the original commit.

Release notes for dep_update

---

gating/check/run

Do not lint playbooks imported from other repositories that we cannot
modify

CEPHSTORA-462 Lint should ignore ceph-ansible play

---

gating/check/run
maas-ceph-rpco.sh
tests/maas-ceph-vars.yml

Sets up the groups for cinder_(volume|api|scheduler|all) to install cinder maas checks.

CEPHSTORA-448 Install maas ceph with rpco

---

releasenotes/notes/pin_by_default-2a410a82d5bcc398.yaml
tests/host_vars/mds1.yml
tests/setup-ceph-aio.yml
tests/test-version.yml

Adding a check all gates to confirm that the ceph version pinning is
working and only the version of ceph we are expecting is installed.
Fixed an issue with the mds container in the tests missing the storage
network.

CEPHSTORA-489 Add ceph pinning test

---

playbooks/group_vars/all/00-defaults.yml
releasenotes/notes/openstack_config_default-982094b45c957a84.yaml

In most cases we are deploying Ceph to back openstack and will need
these pools.  For standalone ceph installs we will need to override
openstack_config to False or clean up the extra pools and auth that will
be created.

CEPHSTORA-268 Add openstack pools by default

---

gating/check/run
tests/setup-ceph-aio.yml
tests/test-ceph-aio.yml

Upgrading to ceph-ansible 3.1.x is producing false positives in the
rpc-ceph gates due to the inclusion of installer status as part of
ceph-ansible.  Breaking the test plays out to separate runs so ones
plays status does mask an error in another play.

CEPHSTORA-493 Fix gating false positives

---

gating/update_dependencies/run

The update_dependencies gate is not including the release note that it
creates.  Using git add to ensure the release note gets included the
next time the gate runs.

CEPHSTORA-367 Update_dep gate not including renote

---

playbooks/add-repo.yml

Add commands to the add-repo.yml play to create the i386 metadata

CEPHSTORA-505 Ceph local repo missing i386 md

---

tests/test-rgw.yml

Add a retry loop to the swift upload test and wait for port to avoid
failing the upload because RGW is not ready yet.

CEPHSTORA-526 Add retry loop for swift test

---

tests/inventory

This group does not appear to utilized by any of the existing test
scenarios. This change will natively allow rpc-maas to deploy within
ceph aio scenarios used by this inventory source. Reference: NATT-26.
Signed-off-by: Nathan Pawelek <nathan.pawelek@rackspace.com>

Modify tests/inventory hosts group

---

README.md

This is no longer being used after the last re-org.  We
depend on the upstream ceph-ansible and any deployment
tool documentation for future installs.

rpc-ceph decom
